#!/bin/bash -ex
trap 'chown -R --reference /build-inside/build-package /out/' EXIT

echo "Building .deb package..."

TARGET=${GOPATH}/src/${FULLNAME}
mkdir -p ${TARGET}
rsync -a /source/* ${TARGET}/
cd ${TARGET}
make
make upx
make install

/usr/bin/${NAME} --generate-config

cd /out
fpm -t deb -s dir -n ${NAME} --version ${VERSION} --description "${DESCRIPTION}" \
    --url "${URL}" --license "${LICENSE}" --vendor "${VENDOR}" --maintainer "${MAINTAINER}" \
    --config-files /etc/${NAME}/config.json \
    --deb-systemd /etc/systemd/system/${NAME}.service \
    -C / /usr/bin/${NAME} /etc/${NAME}/config.json
