#!/bin/bash -ex
# enter the directory where the build script is located
cd "${0%/*}"

set -o allexport
. ../env.list
set +o allexport

SRC_DIR="$(pwd)/../../"
CURRENT_DISTRO=$(basename $(pwd))
BUILD_IMAGE="${NAME}-${CURRENT_DISTRO}-build"

# create the build image from the provided directory
docker build --build-arg GOLANG_VERSION=${GOLANG_VERSION} --pull -t ${BUILD_IMAGE} build-image

# clean previous packages
rm -rf out

docker run --env-file ../env.list --rm -v $(pwd)/build-inside:/build-inside:ro -v ${SRC_DIR}:/source:ro -v $(pwd)/out:/out -w /build-inside ${BUILD_IMAGE} /build-inside/build-package
